### ISSUE TITLE
Doesn't install OS6

### ISSUE THREAD

**Issue by grtessman** [Mhynlo/readynas-portainer#2]
Logs:  System: Cannot install application portainer.

ReadyNas OS6 v 6.10.3 

Any chance you could fix this?

**Comment by sacoene** [comment]
I've had the same issue.
The log (install-debpkg.log) indicate the following:

```
Setting up portainer (1.16.4-ml0) ...

Error response from daemon: manifest for portainer/portainer:1.16.4 not found

Unable to find image 'portainer/portainer:1.16.4' locally
```

I checked the [docker hub](https://hub.docker.com/r/portainer/portainer/tags?page=1&name=1.16.4), and indeed, the image `portainer:1.16.4` does not exist (any longer).
I guess they changed/renamed their images.
Easy fix is changing the image that the plugin tries to pull and run, replacing `portainer/portainer:1.16.4` with  `portainer/portainer:linux-amd64-1.16.4`.

This has to be changed in the [prerm](https://github.com/Mhynlo/readynas-portainer/tree/master/debian/prerm) and [postinst](https://github.com/Mhynlo/readynas-portainer/tree/master/debian/postinst).

**Comment by grtessman** [comment]
Awesome!  I'll give it a shot, thank you for the helpful reply.  Seems like it could be an easy fix and pull request to resolve for everyone.

**Comment by grtessman** [comment]
> I've had the same issue.
> The log (install-debpkg.log) indicate the following:
> 
> ```
> Setting up portainer (1.16.4-ml0) ...
> 
> Error response from daemon: manifest for portainer/portainer:1.16.4 not found
> 
> Unable to find image 'portainer/portainer:1.16.4' locally
> ```
> 
> I checked the [docker hub](https://hub.docker.com/r/portainer/portainer/tags?page=1&name=1.16.4), and indeed, the image `portainer:1.16.4` does not exist (any longer).
> I guess they changed/renamed their images.
> Easy fix is changing the image that the plugin tries to pull and run, replacing `portainer/portainer:1.16.4` with `portainer/portainer:linux-amd64-1.16.4`.
> 
> This has to be changed in the [prerm](https://github.com/Mhynlo/readynas-portainer/tree/master/debian/prerm) and [postinst](https://github.com/Mhynlo/readynas-portainer/tree/master/debian/postinst).

Any chance you can tell me how to install this once I've made the changes in my fork?  I don't have a deb file...   Thank you!

**Comment by Mhynlo** [comment]
Thanks @grtessman for the PR.
I have approved the PR and created an updated build here:
https://github.com/Mhynlo/readynas-portainer/releases/tag/1.16.4-ml1

Please try uploading the deb file that is in that release.

**Comment by grtessman** [comment]
It works!  I really appreciate the pull approval and you building the
package!

Thank you so much!
